site_name: Accelerators Guidebook
site_description: Repository for Business Accelerators 
site_url: https://salahmokhayesh.github.io/accelerators/
repo_name: SalahMokhayesh/accelerators
repo_url: https://github.com/SalahMokhayesh/accelerators
edit_uri: edit/main/docs/


theme:
name: material
features:
- navigation.tabs
- navigation.sections
- navigation.expand
- navigation.indexes
- content.code.copy
- toc.integrate
- search.suggest
- search.highlight
palette:
- scheme: default
primary: indigo
accent: indigo
logo: _assets/logo.png
favicon: _assets/logo.png


plugins:
- search
- git-revision-date-localized:
enable_creation_date: true


markdown_extensions:
- admonition
- attr_list
- md_in_html
- toc:
permalink: true
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.highlight


nav:
- Home: index.md
- Accelerators:
- Architecture: architecture/index.md
- Code Converter: code-converter/index.md
- Data Buddy: data-buddy/index.md
- MDM: mdm/index.md
- Sidecar Applications: sidecar-applications/index.md
- Synthetic Data Generator: synthetic-data-generator/index.md
- Test Data: test-data/index.md
- Project:
- Contributing: contributing.md
- Changelog: changelog.md