site_name: Data Governance and Accelerators
site_description: Data Governance and Accelerators — docs and how-tos
site_url: https://salahmokhayesh.github.io/accelerators/
repo_name: SalahMokhayesh/accelerators
repo_url: https://github.com/SalahMokhayesh/accelerators
edit_uri: edit/main/docs/

theme:
  name: material
  logo: _assets/pellera-logo.png
  favicon: _assets/pellera-logo.png
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - header.autohide
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple

extra_css:
  - _assets/styles.css

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Data Governance:
      - Overview: data-governance/index.md
      - Assessment Questions: data-governance/assessment.md
  - Accelerators:
      - Architecture: architecture/index.md
      - Code Converter: code-converter/index.md
      - Data Buddy: data-buddy/index.md
      - MDM: mdm/index.md
      - Sidecar Applications: sidecar-applications/index.md
      - Synthetic Data Generator: synthetic-data-generator/index.md
      - Test Data: test-data/index.md
  - Project:
      - Contributing: contributing.md
      - Changelog: changelog.md
