site_name: Data Governance - Deliverables and Accelerators
repo_url: https://github.com/SalahMokhayesh/accelerators
docs_dir: docs

theme:
  name: material
  logo: _assets/pellera-logo.png
  favicon: _assets/pellera-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple

extra_css:
  - _assets/styles.css   # ✔ stylesheet lives in docs/_assets/

plugins:
  - search

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# NEW: contact info for header/footer and meta
site_author: Salah Mokhayesh
extra:
  contact:
    name: "Salah Mokhayesh | Lead Data Governance"
    org: "Pellera Technologies"
    phone: "M 734-262-5040"
    email: "Salah.Mokhayesh@pellera.com"
    website: "https://pellera.com"
  social:
    - icon: material/email
      link: mailto:Salah.Mokhayesh@pellera.com
      name: Email Salah Mokhayesh
    - icon: material/phone
      link: tel:+17342625040
      name: Call 734-262-5040
    - icon: material/web
      link: https://pellera.com
      name: pellera.com

nav:
  - Home: index.md
  - Data Governance:
      - Overview: data-governance/index.md
      - Assessment Questions: data-governance/assessment.md
  - Accelerators:
      - Prompt Engineering: prompt-engineering/index.md
      - Code Converter: code-converter/index.md
      - Data Buddy:
          - Overview: data-buddy/index.md
          - Data Profiling: data-buddy/data-profiling.md
          - Data Quality: data-buddy/data-quality.md
          - Data Cataloging: data-buddy/data-cataloging.md
          - Anomaly Detection: data-buddy/anomaly-detection.md
          - Compliance: data-buddy/compliance.md
          - Workflow Automation: data-buddy/workflow-automation.md
          - Conversational AI: data-buddy/conversational-ai.md
          - Knowledge Files: data-buddy/knowledge-files.md
      - MDM: mdm/index.md
      - Sidecar Applications: sidecar-applications/index.md
      - Synthetic Data Generator: synthetic-data-generator/index.md
  - Project:
      - Contributing: contributing.md
      - Changelog: changelog.md
  - Contact: contact.md
