site_name: Data Governance and Accelerators
repo_url: https://github.com/SalahMokhayesh/accelerators
docs_dir: docs

theme:
  name: material
  logo: _assets/pellera-logo.png
  favicon: _assets/pellera-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - styles.css

plugins:
  - search   # ← removed git-revision-date-localized to avoid missing-plugin error

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Data Governance:
      - Overview: data-governance/index.md
      - Assessment Questions: data-governance/assessment.md
  - Accelerators:
      - Prompt Engineering: prompt-engineering/index.md
      - Code Converter: code-converter/index.md
      - Data Buddy:
          - Overview: data-buddy/index.md
          - Data Profiling: data-buddy/data-profiling.md
          - Data Quality: data-buddy/data-quality.md
          - Data Cataloging: data-buddy/data-cataloging.md
          - Anomaly Detection: data-buddy/anomaly-detection.md
          - Compliance: data-buddy/compliance.md
          - Workflow Automation: data-buddy/workflow-automation.md
          - Conversational AI: data-buddy/conversational-ai.md
          - Knowledge Files: data-buddy/knowledge-files.md
      - MDM: mdm/index.md
      - Sidecar Applications: sidecar-applications/index.md
      - Synthetic Data Generator: synthetic-data-generator/index.md
      # If docs/test-data/ still exists and you use --strict, keep the next line.
      # Remove it after you delete that folder.
      # - Test Data (temp): test-data/index.md
  - Project:
      - Contributing: contributing.md
      - Changelog: changelog.md
